on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    # permissions on the GITHUB_TOKEN for semantic-release
    # see https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/github-actions.md
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests

    steps:
      - uses: actions/checkout@v4
      # https://github.com/actions/setup-node#usage
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run build
      # https://github.com/actions/upload-pages-artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "./apps/browser-example/dist/"

      # do the semantic-release release notes
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # TODO: NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx semantic-release@24

  pages:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # https://github.com/actions/deploy-pages & https://github.com/actions/starter-workflows/blob/main/pages/static.yml
      - uses: actions/deploy-pages@v4
        id: deployment
